= spring-jms-xa

This repository demonstrates a problem with spring-jms when more than 9 concurrent consumers in conjunction with the default task executor (see link:https://github.com/spring-projects/spring-framework/blob/ea52ecc5e08a14869ec351af38481c4008c8bcd8/spring-jms/src/main/java/org/springframework/jms/listener/DefaultMessageListenerContainer.java#L764-L768[here (`github.com`)]) is used.

In this case, we loose some XA-properties. When the transaction is rolled back, the message is consumed and no longer on the queue.

== Project setup
Branch `main` uses narayana as transaction-manager; branch `atomikos` uses atomikos as trasnaction manager. Both branches behave identical wrt. test outcome.

The container factory is configured in link:src/main/java/de/turing85/spring/boot/jms/xa/config/BeanProvider.java[]. We have one abstract base test class in link:src/test/java/de/turing85/spring/boot/jms/xa/listener/executor/BaseTest.java[], providing two tests: one happy path test, one rollback test.

The actual tests:

- link:src/test/java/de/turing85/spring/boot/jms/xa/listener/executor/deflt/WithNineConsumerAndDefaultTest.java[]
- link:src/test/java/de/turing85/spring/boot/jms/xa/listener/executor/deflt/WithTenConsumersAndDefaultTest.java[]
- link:src/test/java/de/turing85/spring/boot/jms/xa/listener/executor/threadpool/threads/nine/WithNineConsumersAndThreadPoolNineThreadsTest.java[]
- link:src/test/java/de/turing85/spring/boot/jms/xa/listener/executor/threadpool/threads/nine/WithTenConsumersAndThreadPoolNineThreadsTest.java[]
- link:src/test/java/de/turing85/spring/boot/jms/xa/listener/executor/threadpool/threads/ten/WithNineConsumersAndThreadPoolTenThreadsTest.java[]
- link:src/test/java/de/turing85/spring/boot/jms/xa/listener/executor/threadpool/threads/ten/WithTenConsumersAndThreadPoolTenThreadsTest.java[]

configure the container differently. All tests succeed, except for:

- `WithTenConsumersAndDefaultTest:roolbackTest`, and
- `WithTenConsumersAndThreadPoolTenThreadsTest::rollbackTest`

== Test execution
In order to execute the tests, a docker or docker-compatible container runtime, as well as a working testcontainers-setup is needed.

We can run the tests by executing
.Run test
[source, bash]
----
./mvnw clean test
----

== Contributors ✨

Thanks goes to these wonderful people (https://allcontributors.org/docs/en/emoji-key[emoji key]):

++++
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->
<table>
  <tbody>
    <tr>
      <td align="center" valign="top" width="14.28%"><a href="https://turing85.github.io"><img src="https://avatars.githubusercontent.com/u/32584495?v=4?s=100" width="100px;" alt="Marco Bungart"/><br /><sub><b>Marco Bungart</b></sub></a><br /><a href="#code-turing85" title="Code">💻</a> <a href="#maintenance-turing85" title="Maintenance">🚧</a> <a href="#doc-turing85" title="Documentation">📖</a></td>
      <td align="center" valign="top" width="14.28%"><a href="https://zhfeng.github.io/"><img src="https://avatars.githubusercontent.com/u/1246139?v=4?s=100" width="100px;" alt="Zheng Feng"/><br /><sub><b>Zheng Feng</b></sub></a><br /><a href="https://github.com/quarkiverse/quarkus-artemis/commits?author=zhfeng" title="Code">💻</a> <a href="#maintenance-zhfeng" title="Maintenance">🚧</a></td>
    </tr>
  </tbody>
</table>

<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->

<!-- ALL-CONTRIBUTORS-LIST:END -->
++++

This project follows the link:https://github.com/all-contributors/all-contributors[all-contributors] specification. Contributions of any kind welcome!
